-- Um Tempo com Deus
-- Banco para autenticação, perfil e registros pessoais.
-- Execute este arquivo no SQL Editor do seu projeto Supabase.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default 'Usuário',
  updated_at timestamptz not null default now()
);

create table if not exists public.user_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('verse','note','reflection','activity')),
  local_id text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, type, local_id)
);

create index if not exists user_records_user_id_idx
  on public.user_records(user_id);

alter table public.profiles enable row level security;
alter table public.user_records enable row level security;

revoke all on table public.profiles from anon;
revoke all on table public.user_records from anon;

grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.user_records to authenticated;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "profiles_delete_own" on public.profiles;
create policy "profiles_delete_own"
on public.profiles
for delete
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "records_select_own" on public.user_records;
create policy "records_select_own"
on public.user_records
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "records_insert_own" on public.user_records;
create policy "records_insert_own"
on public.user_records
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "records_update_own" on public.user_records;
create policy "records_update_own"
on public.user_records
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "records_delete_own" on public.user_records;
create policy "records_delete_own"
on public.user_records
for delete
to authenticated
using ((select auth.uid()) = user_id);

-- Permissões necessárias para as tabelas protegidas.
grant usage, select on sequence public.user_records_id_seq to authenticated;
